"""Generate exact SVG figures from the checked-in specification and evidence.
Run from any directory. --check compares generated bytes with committed figures.
No external service or image model is used. Numerical rows are resolved by JSON path.
"""
import argparse, hashlib, html, json, textwrap
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SPEC = json.loads((ROOT/'docs/figure_spec.json').read_text())
def esc(s): return html.escape(str(s), quote=True)
def lines(text,x,y,width=68,size=23,color='#23354b',weight='400'):
    out=[]
    for i,line in enumerate(textwrap.wrap(str(text),width=width,break_long_words=False)):
        out.append(f'<text x="{x}" y="{y+i*(size+9)}" font-family="DejaVu Sans,Arial,sans-serif" font-size="{size}" fill="{color}" font-weight="{weight}">{esc(line)}</text>')
    return ''.join(out)
def base(title,subtitle):
    return '<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="840" viewBox="0 0 1200 840" role="img"><title>'+esc(title)+'</title><desc>'+esc(subtitle)+'</desc><rect width="1200" height="840" fill="#f6f8fc"/>'+lines(title,48,60,1000,min(29,int(1090/max(len(title)*.66,1))),'#133b65','700')+lines(subtitle,48,111,96,18,'#526278')
def panel(label,text,y,height,color):
    return f'<rect x="42" y="{y}" width="1116" height="{height}" rx="10" fill="white" stroke="#d2dce7"/><rect x="42" y="{y}" width="7" height="{height}" fill="{color}"/>'+lines(label,65,y+32,95,18,color,'700')+lines(text,65,y+68,89,22)
def build():
    s=SPEC
    out=base('01 / '+s['question'],s['status'])
    out+=panel('DATA / OBSERVATION UNIT',s['data'],145,134,'#2365a0')
    out+=panel('DESIGN / COMPARISON',s['method'],295,166,'#128075')
    out+=panel('FINDING / INTERPRETATION',s['finding'],477,270,'#8b4d27')
    out+=lines('Read the calculation guide for source paths, assumptions and reproduction status.',48,796,108,17)
    overview=out+'</svg>\n'
    source=ROOT/s['source']; data=json.loads(source.read_text())
    out=base('02 / Calculation and evidence',s['status'])
    out+=panel('DEFINED CALCULATION',s['formula'],145,142,'#2365a0')
    out+=lines(s['table_title'],60,328,93,20,'#128075','700')
    y=371
    for row in s['rows']:
        value=data
        for key in row['path']: value=value[key]
        if value is None: shown='undefined'
        elif isinstance(value,bool): shown=str(value).lower()
        elif isinstance(value,(int,float)): shown=f'{value:.4f}' if isinstance(value,float) else str(value)
        else: shown=str(value)
        label=row['label'].replace('_',' ')
        out+=f'<rect x="48" y="{y-26}" width="1104" height="51" fill="'+('#eaf0f7' if (y-371)//56%2==0 else '#ffffff')+'"/>'
        out+=lines(label,63,y,57,19)+lines(shown,797,y,18,21,'#133b65','700')+lines(row['unit'],950,y,25,14)
        y+=56
    digest=hashlib.sha256(source.read_bytes()).hexdigest()[:16]
    out+=lines('Source: '+s['source']+' | SHA-256 prefix: '+digest,48,746,110,16)
    out+=lines(s['evidence_note'],48,780,112,16)
    return {'assets/review_overview.svg':overview,'assets/review_calculations.svg':out+'</svg>\n'}
if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--check',action='store_true');args=parser.parse_args()
    for path,text in build().items():
        p=ROOT/path
        if args.check:
            if not p.exists() or p.read_text()!=text: raise SystemExit('Stale figure: '+path)
        else: p.parent.mkdir(parents=True,exist_ok=True);p.write_text(text)
    print('Figure sources and generated SVGs agree.')
